# Generated by Django 4.0 on 2023-03-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinteres', '0003_remove_photo_user_alter_photo_nameuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='nameuser',
            field=models.CharField(blank=True, default='<django.db.models.query_utils.DeferredAttribute object at 0x04C3E958>', max_length=200, null=True),
        ),
    ]
