# Generated by Django 4.0 on 2023-03-04 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinteres', '0004_alter_photo_nameuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='nameuser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pinteres.customuser'),
            preserve_default=False,
        ),
    ]
